groups:
  - name: kafka_alerts
    rules:
      - alert: KafkaBrokerDown
        expr: up{job="kafka-brokers"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Kafka broker down"
          description: "Kafka broker {{ $labels.instance }} has been down for more than 1 minute"

      - alert: KafkaControllerDown
        expr: up{job="kafka-controllers"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Kafka controller down"
          description: "Kafka controller {{ $labels.instance }} has been down for more than 1 minute"
